# Generated by Django 3.1.1 on 2020-10-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRecords',
            fields=[
                ('restaurant_Inspection_ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('borough', models.CharField(max_length=200)),
                ('restaurant_name', models.CharField(max_length=200)),
                ('seating_choice', models.CharField(max_length=200)),
                ('legal_bussiness_name', models.CharField(max_length=200)),
                ('business_address', models.CharField(max_length=200)),
                ('is_sideway_compliant', models.CharField(max_length=200)),
                ('is_roadway_compliant', models.CharField(max_length=200)),
                ('skipped_reason', models.CharField(max_length=200)),
                ('inspected_on', models.DateTimeField()),
                ('agency_code', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('business_id', models.CharField(max_length=200)),
            ],
        ),
    ]
