# Generated by Django 3.1.1 on 2020-10-11 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.RenameField(
            model_name='inspectionrecords',
            old_name='legal_bussiness_name',
            new_name='legal_business_name',
        ),
    ]
