# Generated by Django 3.1.2 on 2020-11-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YelpRestaurantDetails',
            fields=[
                ('business_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('neighborhood', models.CharField(default=None, max_length=200, null=True)),
                ('category', models.CharField(default=None, max_length=200, null=True)),
                ('price', models.CharField(default=None, max_length=200, null=True)),
                ('rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('img_url', models.CharField(default=None, max_length=200, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Zipcodes',
            fields=[
                ('zipcode', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('borough', models.CharField(default=None, max_length=200, null=True)),
                ('neighborhood', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
    ]
