# Generated by Django 3.1.2 on 2020-11-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_auto_20201108_1859"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "category",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                (
                    "parent_category",
                    models.CharField(default=None, max_length=200, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inspectionrecords",
            name="business_id",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="compliant_status",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="business_id",
            field=models.CharField(
                blank=True, default=None, max_length=200, null=True, unique=True
            ),
        ),
        migrations.RemoveField(
            model_name="yelprestaurantdetails",
            name="category",
        ),
        migrations.AddField(
            model_name="yelprestaurantdetails",
            name="category",
            field=models.ManyToManyField(blank=True, to="restaurant.Categories"),
        ),
    ]
