# Generated by Django 3.1.2 on 2020-11-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_yelprestaurantdetails_zipcodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_business_id', models.CharField(max_length=200)),
                ('safety_level', models.CharField(max_length=1)),
                ('temperature_required', models.CharField(default='False', max_length=5)),
                ('contact_info_required', models.CharField(default='False', max_length=5)),
                ('employee_mask', models.CharField(default='False', max_length=5)),
                ('capacity_compliant', models.CharField(default='False', max_length=5)),
                ('distance_compliant', models.CharField(default='False', max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='yelprestaurantdetails',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='yelprestaurantdetails',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, default=0, max_digits=17),
        ),
    ]
