# Generated by Django 3.1.2 on 2020-10-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20201012_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='business_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
