# Generated by Django 3.1.2 on 2020-11-23 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20201109_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='business_id',
            field=models.ForeignKey(blank=True, default=1, max_length=200, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='restaurant.yelprestaurantdetails', unique=True),
        ),
    ]
