# Generated by Django 3.1.2 on 2020-10-13 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20201012_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionrecords',
            name='agency_code',
        ),
        migrations.RemoveField(
            model_name='inspectionrecords',
            name='is_sideway_compliant',
        ),
    ]
