# Generated by Django 3.1.1 on 2020-10-11 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='legal_business_name',
            new_name='business_address',
        ),
    ]
