# Generated by Django 3.1.2 on 2020-11-23 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20201123_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='yelp_detail',
            field=models.ForeignKey(blank=True, default=1, max_length=200, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='restaurant.yelprestaurantdetails', unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='business_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, unique=True),
        ),
    ]
