# Generated by Django 3.1.2 on 2020-10-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20201012_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionrecords',
            name='inspected_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
