# Generated by Django 3.1.1 on 2020-10-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20201011_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='business_id',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together={('restaurant_name', 'business_address', 'postcode')},
        ),
    ]
