# Generated by Django 3.1.2 on 2020-10-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20201011_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionrecords',
            name='borough',
        ),
        migrations.RemoveField(
            model_name='inspectionrecords',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='inspectionrecords',
            name='legal_business_name',
        ),
        migrations.RemoveField(
            model_name='inspectionrecords',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='inspectionrecords',
            name='seating_choice',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='legal_business_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together={('restaurant_name', 'legal_business_name', 'postcode')},
        ),
    ]
