# Generated by Django 3.1.2 on 2020-10-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20201012_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionrecords',
            name='inspected_on',
            field=models.CharField(max_length=200),
        ),
    ]
