# Generated by Django 3.1.2 on 2020-10-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20201012_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionrecords',
            name='inspected_on',
            field=models.DateTimeField(),
        ),
    ]
