# Generated by Django 3.1.2 on 2020-10-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20201012_2126'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together={('restaurant_name', 'business_address', 'postcode')},
        ),
    ]
