# Generated by Django 3.1.2 on 2020-11-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20201123_0735'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinesafelyuser',
            name='preferences',
            field=models.ManyToManyField(blank=True, to='restaurant.Categories'),
        ),
    ]
