# Generated by Django 3.1.2 on 2020-11-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20201109_2122'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinesafelyuser',
            name='preference',
            field=models.ManyToManyField(blank=True, to='restaurant.Categories'),
        ),
    ]
